### PR TITLE
Release CRA preset

### LINKED ISSUE #38: CRA preset broken on Windows
The preset works fine on macOS, however on Windows met with an error when trying to `start-storybook`:

```
ERR! Error: Cannot find module 'C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\config\webpack.config'
ERR! Require stack:
ERR! - C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\preset-create-react-app\index.js
ERR! - C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\core\dist\server\presets.js
ERR! - C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\core\dist\server\config.js
ERR! - C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\core\dist\server\build-static.js
ERR! - C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\core\server.js
ERR! - C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\react\dist\server\index.js
ERR! - C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\react\bin\index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:685:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:838:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at Object.webpack (C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\preset-create-react-app\index.js:55:28)
ERR!     at C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\core\dist\server\presets.js:82:72
ERR!     at async Promise.all (index 1)
ERR!     at async buildDevStandalone (C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\core\dist\server\build-dev.js:332:9)
ERR!     at async buildDev (C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\@storybook\core\dist\server\build-dev.js:411:3)
ERR!  Error: Cannot find module 'C:\Projects\Anglo American\AD Core\da-ad-core-ui\node_modules\config\webpack.config'
...
```

It appears as though `getReactScriptsPath()` isn't returning what is expected on Windows.

Tested on both Node v10.16.3 and v12.11.1.

Using `react-scripts@3.1.2`.

### PR DESCRIPTION
**Pull request by mrmckeb**
This PR should resolve #38, and fixes a typo in the README (that I was sure I had fixed).

With this, I think we can release 1.0.0.

### CODE REVIEW

File: packages/preset-create-react-app/helpers/getReactScriptsPath.js [hunk 1]
```diff
@@ -4,16 +4,19 @@ const path = require('path');
...
    * Try to find the scripts package by following the `react-scripts` symlink.
    * This won't work for Windows users, unless within WSL.
    */
-  try {
-    const resolvedBinPath = fs.realpathSync(scriptsBinPath);
-    const scriptsPath = path.join(resolvedBinPath, '..', '..');
-    return scriptsPath;
-  } catch (e) {
-    // NOOP
+  if (process.platform !== 'win32') {
```
Comment (shilman) [inline packages/preset-create-react-app/helpers/getReactScriptsPath.js]: Why not put this in the else clause?

Comment (shilman) [reply packages/preset-create-react-app/helpers/getReactScriptsPath.js]: Or put the other case in the else clause?
